### ISSUE TITLE
Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by Vincent-Du-Hello** [BentoBoxWorld/AcidIsland#106]
This is the message:
[15:12:37 ERROR]: Could not load 'plugins/AcidIsland-1.14.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.4.jar:git-Paper-414]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.4.jar:git-Paper-414]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more

And I found NO plugin.yml in the JAR file, too.

**Comment by BONNe** [comment]
Acid island is not a plugin, but an add-on for BentoBox plugin.
https://docs.bentobox.world/en/latest/BentoBox/Install-Bentobox/#install-addons

**Comment by tastybento** [comment]
You can also download everything you need from https://download.BentoBox.world
