### ISSUE TITLE
I have some problems and need help

### ISSUE THREAD

**Issue by YYC2001** [BentoBoxWorld/AcidIsland#109]
### Description
####Describe the error
<! -A clear and concise description of the problem you're encountering ->
Encountered some errors, bentobox seems to be unavailable

####Steps to reproduce the behavior
<! -Step-by-step instructions for us to reproduce the bug on our side. ->I don’t know how to reproduce

####Expected behavior
<! -do not know? ->

####Screenshots and videos (optional)
<! -Videos and screenshots are very useful because they can provide better information about your problem. ->

### surroundings

#####`/ bbox version` output (required)
<! -Paste the output of `/bbox version` into the code block below (remove the underscore). No images are provided. ->
```
 [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent on method "public void world.bentobox.biomes.listeners.ChangeOwnerListener.onTeamSetOwnerEvent(world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling Challenges (0.8.2)...
[15:14:55] [Server thread/INFO]: [BentoBox] [Challenges] Loading challenges...
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling ControlPanel (1.7.0)...
[15:14:55] [Server thread/INFO]: [BentoBox] Loading control panels...
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling DimensionalTrees (1.6.0)...
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling Level (2.0.0)...
[15:14:55] [Server thread/INFO]: [BentoBox] [Level] Loaded TopTen for acidisland_world
[15:14:55] [Server thread/INFO]: [BentoBox] [Level] Level hooking into AcidIsland
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onNewIslandOwner(world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.island.IslandEvent$IslandCreatedEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onNewIsland(world.bentobox.bentobox.api.events.island.IslandEvent$IslandCreatedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.island.IslandEvent$IslandResettedEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onNewIsland(world.bentobox.bentobox.api.events.island.IslandEvent$IslandResettedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.island.IslandEvent$IslandUnregisteredEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onIsland(world.bentobox.bentobox.api.events.island.IslandEvent$IslandUnregisteredEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.island.IslandEvent$IslandRegisteredEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onIsland(world.bentobox.bentobox.api.events.island.IslandEvent$IslandRegisteredEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamLeaveEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onIsland(world.bentobox.bentobox.api.events.team.TeamEvent$TeamLeaveEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamKickEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onIsland(world.bentobox.bentobox.api.events.team.TeamEvent$TeamKickEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamJoinedEvent on method "public void world.bentobox.level.listeners.IslandTeamListeners.onIsland(world.bentobox.bentobox.api.events.team.TeamEvent$TeamJoinedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling Limits (1.12.2)...
[15:14:55] [Server thread/ERROR]: [BentoBox] [Limits] Unknown entity type: pig_ZOMbIe - skipping...
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Entity limits:
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Limit ENDERMAN to 5
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Limit CHICKEN to 10
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Limits will apply to AcidIsland
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Loading default limits
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Limit HOPPER to 10
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Loading limits for acidisland_world
[15:14:55] [Server thread/INFO]: [BentoBox] [Limits] Limit HOPPER to 11
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.island.IslandEvent$IslandDeleteEvent on method "public void world.bentobox.limits.listeners.BlockLimitsListener.onIslandDelete(world.bentobox.bentobox.api.events.island.IslandEvent$IslandDeleteEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent on method "public void world.bentobox.limits.listeners.JoinListener.onOwnerChange(world.bentobox.bentobox.api.events.team.TeamEvent$TeamSetownerEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/INFO]: [BentoBox] Enabling Warps (1.9.3)...
[15:14:55] [Server thread/INFO]: [BentoBox] [Warps] Loading warps...
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamLeaveEvent on method "public void world.bentobox.warps.listeners.WarpSignsListener.onPlayerLeave(world.bentobox.bentobox.api.events.team.TeamEvent$TeamLeaveEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/WARN]: [BentoBox] "BentoBox v1.16.1" has registered a listener for world.bentobox.bentobox.api.events.team.TeamEvent$TeamKickEvent on method "public void world.bentobox.warps.listeners.WarpSignsListener.onPlayerLeave(world.bentobox.bentobox.api.events.team.TeamEvent$TeamKickEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [tastybento, Poslovitch].
[15:14:55] [Server thread/INFO]: [BentoBox] Addons successfully enabled.
[15:14:55] [Server thread/ERROR]: [BentoBox] *****************CRITIAL ERROR!******************
[15:14:55] [Server thread/ERROR]: [BentoBox] Island distance mismatch!
World 'acidisland_world' distance 192 != island range 64!
Island ID in database is AcidIsland24f88041-4ef5-4463-bfa1-7db12e13ae7d.
Island distance in config.yml cannot be changed mid-game! Fix config.yml or clean database.
[15:14:55] [Server thread/ERROR]: [BentoBox] Could not load islands! Disabling BentoBox...
[15:14:55] [Server thread/ERROR]: [BentoBox] *************************************************
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling addons...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling AcidIsland...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling Biomes...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling Challenges...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling ControlPanel...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling DimensionalTrees...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling Level...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling Limits...
[15:14:55] [Server thread/INFO]: [BentoBox] Disabling Warps...
[15:14:55] [Server thread/INFO]: [BentoBox] Addons successfully disabled.
[15:14:55] [Server thread/INFO]: [BentoBox] Removing coops from islands...
[15:14:55] [Server thread/INFO]: [BentoBox] Saving islands - this has to be done sync so it may take a while with a lot of islands...
[15:14:55] [Server thread/INFO]: [BentoBox] Islands saved.
[15:14:55] [Server thread/INFO]: [BentoBox] Closing database.
[15:14:55] [Server thread/INFO]: [TrMenu] INFO | 加载完毕. TrMenu v1.21 现已启用, 敬请使用.
[15:14:55] [Server thread/INFO]: [QuickShop] Registering BStats Mertics...
[15:14:55] [Craft Scheduler Thread - 9/INFO]: [Essentials] §6Fetching version information...
[15:14:55] [Server thread/INFO]: [QuickShop] Metrics submitted.
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [PlaceholderAPI] Fetching available expansion information...
[15:14:55] [Server thread/INFO]: [AncientGates] Loading gates from disk
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [PlaceholderAPI] Fetching available expansion information...
[15:14:55] [Server thread/INFO]: [AncientGates] Loading gates into memory
[15:14:55] [Server thread/INFO]: [AncientGates] Finished - 22 ms
[15:14:55] [Server thread/INFO]: [QuickShop] Using economy system: Essentials Economy
[15:14:55] [Server thread/INFO]: [BentoBox] Added world AcidIsland (NORMAL)
[15:14:55] [Craft Scheduler Thread - 11/INFO]: [Vault] Checking for Updates ...
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded Blueprint Bundle 'default' for AcidIsland.
[15:14:55] [Server thread/INFO]: [TrMenu] INFO | 成功加载了 5 个有效菜单... [50 Ms]
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded blueprint '1' for AcidIsland
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded blueprint 'end-island' for AcidIsland
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded blueprint 'island' for AcidIsland
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded blueprint 'nether-island' for AcidIsland
[15:14:55] [Craft Scheduler Thread - 0/INFO]: [BentoBox] Loaded blueprint 'temple' for AcidIsland
[15:14:56] [Server thread/INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.10.9) is available at:
[15:14:56] [Server thread/INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer] ----------------------------------------------
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     +===============+
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     | SkinsRestorer |
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     |---------------|
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     |  Bukkit only  |
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     +===============+
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer] ----------------------------------------------
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     Current version: 14.0.2
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer]     This is the latest version!
[15:14:56] [Craft Scheduler Thread - 5/INFO]: [SkinsRestorer] ----------------------------------------------
[15:14:56] [Craft Scheduler Thread - 4/INFO]: [WorldMania] Could not load translations from github
[15:14:57] [Craft Scheduler Thread - 6/INFO]: [PlaceholderAPI] 183 placeholder expansions are available on the cloud.
[15:14:57] [Craft Scheduler Thread - 7/INFO]: [PlaceholderAPI] 183 placeholder expansions are available on the cloud.
[15:14:57] [Craft Scheduler Thread - 6/INFO]: [PlaceholderAPI] 1 installed expansions have updates available.
[15:14:57] [Craft Scheduler Thread - 7/INFO]: [PlaceholderAPI] 1 installed expansions have updates available.
[15:14:57] [Craft Scheduler Thread - 14/INFO]: [PlaceholderAPI] 183 placeholder expansions are available on the cloud.
[15:14:57] [Craft Scheduler Thread - 14/INFO]: [PlaceholderAPI] 1 installed expansions have updates available.
[15:14:58] [Craft Scheduler Thread - 11/INFO]: [Vault] No new version available
[15:15:23] [Craft Scheduler Thread - 0/WARN]: [BentoBox] Plugin BentoBox v1.16.1 generated an exception while executing task 111
java.lang.NullPointerException: null
        at world.bentobox.challenges.web.WebManager.requestCatalogGitHubData(WebManager.java:67) ~[?:?]
        at world.bentobox.challenges.web.WebManager.lambda$new$1(WebManager.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_291]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[15:15:53] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[15:15:53] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:15:53] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:15:53] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:15:53] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:15:53] [Server thread/WARN]:        at io.izzel.taboolib.module.inject.TScheduleLoader$2.run(TScheduleLoader.java:65)
[15:15:53] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[15:15:53] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[15:15:53] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060)
[15:15:53] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
[15:15:53] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[15:15:53] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[15:15:53] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[15:15:53] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[15:15:53] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: io.izzel.taboolib.TabooLibAPI.debug(Lorg/bukkit/plugin/Plugin;[Ljava/lang/String;)V
[15:15:53] [Server thread/WARN]:        at me.arasple.mc.trmenu.bstats.MetricsHandler.reloadStatiscs(MetricsHandler.java:100)
[15:15:53] [Server thread/WARN]:        ... 13 more
```

####Plugin (optional)
<! -Paste the output of `/plugins` into the code block below (remove the underscore). No images are provided. ->
```
LuckPerms, OreTeleport, PlaceholderAPI, VillagerOptimiser, ProtocolLib, TrMenu, SkinsRestorer, Geyser-Spigot, Vault, WorldEdit, WorldGuard, BentoBox, MobsToEggs, WorldMania, NexEngine, Multiverse-Core, Multiverse-Inventories, GoldenEnchants, AncientGates, ResidenceHub, Essential EssentialsProtect, EssentialsChat, EssentialsSpawn, QuickShop, QSGUI
```
 
###Other context (optional)
<! -Any other information you want to provide us. ->
<! -Please type below this line. ->
Error messages and there may be some other plug-ins (other plug-ins are working normally, I mean the error messages of bentobox), don't care about them.

**Comment by tastybento** [comment]
You AcidIsland config.yml must have been deleted some how and it changed to different defaults. 

Edit config.yml to use these settings:
```
  # Radius of island in blocks. (So distance between islands is twice this)
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  distance-between-islands: 64
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /acid range set <player> <new range>
  # or set this permission: acidisland.island.range.<number>
  protection-range: 50
```
Then restart.

FYI The problem is reported here in the log:
```
[15:14:55] [Server thread/ERROR]: [BentoBox] *****************CRITIAL ERROR!******************
[15:14:55] [Server thread/ERROR]: [BentoBox] Island distance mismatch!
World 'acidisland_world' distance 192 != island range 64!
Island ID in database is AcidIsland24f88041-4ef5-4463-bfa1-7db12e13ae7d.
Island distance in config.yml cannot be changed mid-game! Fix config.yml or clean database.
[15:14:55] [Server thread/ERROR]: [BentoBox] Could not load islands! Disabling BentoBox...
[15:14:55] [Server thread/ERROR]: [BentoBox] *************************************************
```
