### ISSUE TITLE
Asynchronous Chunk getEntities call! console flood on 1.17

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#112]
#### Describe the bug

Asynchronous Chunk getEntities call! console flood on 1.17

#### Steps to reproduce the behavior

Run plugin on 1.17 Paper.

#### Expected behavior

No Asynchronous Chunk getEntities call! console flood on 1.17.

##### Output of `/bbox version` (Mandatory)

```
[17:09:06 INFO]: Fut PAPER 1.17.
[17:09:06 INFO]: BentoBox verzió: 1.17.0-SNAPSHOT-LOCAL
[17:09:06 INFO]: Adatbázis: JSON
[17:09:06 INFO]: Betöltött játékvilágok:
[17:09:06 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[17:09:06 INFO]: Betöltött kiegészítők:
[17:09:06 INFO]: AcidIsland 1.14.7-SNAPSHOT-b936 (ENABLED)
[17:09:06 INFO]: Biomes 1.14.1-SNAPSHOT-b204 (ENABLED)
[17:09:06 INFO]: Challenges 0.8.5-SNAPSHOT-b449 (ENABLED)
[17:09:06 INFO]: Chat 1.1.3 (ENABLED)
[17:09:06 INFO]: ControlPanel 1.13.1-SNAPSHOT-b49 (ENABLED)
[17:09:06 INFO]: DimensionalTrees 1.6.1-SNAPSHOT-b82 (ENABLED)
[17:09:06 INFO]: Greenhouses 1.5.3-SNAPSHOT-b296 (ENABLED)
[17:09:06 INFO]: Level 2.6.3-SNAPSHOT-b449 (ENABLED)
[17:09:06 INFO]: MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b225 (ENABLED)
[17:09:06 INFO]: Warps 1.11.0-SNAPSHOT-b284 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (90): Admin-Chat, ajLeaderboards, AntiArmorStandStack, antiRedstoneClock, ArmorStandEditor, AutoMessage, BentoBox, BetterGUI, BungeeHelpop, BuntetesLogolo, BuycraftX, ChangeSkin, ChatControlRed, ChatReaction, ChestShop, ChestSort, Citizens, CMILib, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CustomCrafting, DyedBackpacks, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EventekGUI, EventRendszer, F3NPerm, FarmLimiter, FluffyMachines, HeadDatabase, HolographicDisplays, HonapStaffja, InfinityExpansion, Jatekido, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NashornPlus, NoCheatPlus, OpenInv, PlaceholderAPI, PlugMan, PocketGames, PomaBot, PomaDrops, PotionArmors, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, ShopGUIPlus, Shopkeepers, ShulkerPacks, sleep-most, Slimefun, SlimefunFix, StaffChat, SurvivalInvisiframes, SzulinapiKalapok, TAB, TokenManager, TokenShopEditor, TokenStaff, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags
```
 
### Additional context (Optional)

```
[16:33:15] [Craft Scheduler Thread - 12/WARN]: [BentoBox] Plugin BentoBox v1.17.0-SNAPSHOT-LOCAL generated an exception while executing task 290
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2091) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1169) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at world.bentobox.acidisland.world.AcidTask.getEntityStream(AcidTask.java:103) ~[?:?]
	at world.bentobox.acidisland.world.AcidTask.findEntities(AcidTask.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[16:33:15] [Craft Scheduler Thread - 14/WARN]: [BentoBox] Plugin BentoBox v1.17.0-SNAPSHOT-LOCAL generated an exception while executing task 289
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2091) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1169) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at world.bentobox.acidisland.world.AcidTask.getEntityStream(AcidTask.java:103) ~[?:?]
	at world.bentobox.acidisland.world.AcidTask.findEntities(AcidTask.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"ed5100f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by tastybento** [comment]
Thanks, yes - I found this yesterday. This should fix it.

**Comment by andris155** [comment]
Thanks. This fix works perfectly. :)
