### ISSUE TITLE
Could not pass event CreatureSpawnEvent

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/AcidIsland#119]
### Expected behavior

No error xD

### Observed/Actual behavior

Today I noticed in the console a flood of exception errors, which appear to be related to acid island via perhaps the extramobs plugin. I am having a bit of a hard time properly tracing it back. 

```
[04:09:44 ERROR]: Could not pass event CreatureSpawnEvent to BentoBox v1.19.1-SNAPSHOT-b2194
java.lang.NoSuchFieldError: DEEP_WARM_OCEAN
        at world.bentobox.extramobs.listeners.MobsSpawnListener.onEntitySpawn(MobsSpawnListener.java:118) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1514.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-77]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:729) ~[paper-1.18.1.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:634) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1407) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1319) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:312) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:229) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:187) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1045) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:923) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-77]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

I don't know, I suspect go to /acid island and just idle there waiting for mobs to spawn? The players causing the issue already left, I can't really tell what they were doing, it looked like they were just idling for a while trying to learn about acid island.

### BentoBox version

```
> bbox version
[04:21:12 INFO]: Running PAPER 1.18.1.
[04:21:12 INFO]: BentoBox version: 1.19.1-SNAPSHOT-b2194
[04:21:12 INFO]: Database: JSON
[04:21:12 INFO]: Loaded Game Worlds:
[04:21:12 INFO]: acid (acid): Overworld
[04:21:12 INFO]: cave (cave): Overworld
[04:21:12 INFO]: oneblock (oneblock): Overworld
[04:21:12 INFO]: skyblock (skyblock): Overworld
[04:21:12 INFO]: skygrid (skygrid): Overworld
[04:21:12 INFO]: Loaded Addons:
[04:21:12 INFO]: AcidIsland 1.15.2 (ENABLED)
[04:21:12 INFO]: AOneBlock 1.9.0 (ENABLED)
[04:21:12 INFO]: Biomes 1.14.1-SNAPSHOT-b210 (ENABLED)
[04:21:12 INFO]: Border 3.3.0-SNAPSHOT-b127 (ENABLED)
[04:21:12 INFO]: BSkyBlock 1.15.2-SNAPSHOT-b716 (ENABLED)
[04:21:12 INFO]: CauldronWitchery 2.0.0-SNAPSHOT-#27 (ENABLED)
[04:21:12 INFO]: CaveBlock 1.15.0-SNAPSHOT-b409 (ENABLED)
[04:21:12 INFO]: Challenges 1.0.0-SNAPSHOT-b471 (ENABLED)
[04:21:12 INFO]: ExtraMobs 1.11.0.4-SNAPSHOT-b11 (ENABLED)
[04:21:12 INFO]: Greenhouses 1.6.1-SNAPSHOT-b311 (ENABLED)
[04:21:12 INFO]: Level 2.8.1 (ENABLED)
[04:21:12 INFO]: Likes 2.2.0-SNAPSHOT-b74 (ENABLED)
[04:21:12 INFO]: Limits 1.18.1-SNAPSHOT-b277 (ENABLED)
[04:21:12 INFO]: MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b232 (ENABLED)
[04:21:12 INFO]: SkyGrid 1.18.0-SNAPSHOT-b395 (ENABLED)
[04:21:12 INFO]: TwerkingForTrees 1.4.3 (ENABLED)
[04:21:12 INFO]: Warps 1.11.2-SNAPSHOT-b315 (ENABLED)
>
```
Hardly a few days ago when I upgraded from 1.17.1 to 1.18.1 I've tried my best to clean up the configs and locale files in order to be more 1.18.1 compliant. I waited until the public spigotmc announcement and went to ci to download the jars manually and did some testing. The first 24 ish hours things were fine. I didn't notice 'this' error. Now I do. Hence the report. 

I can imagine in the last 12+ hours there might have been some new jar files, I haven't tested yet.

### Plugin list

n/a, will optionally provide limited if needed, no need to have this in a public ticket.

### Other

Thank you for these gametype/modes, our players love trying them out.

**Comment by BONNe** [comment]
The error is in extra mobs addon. Forgot that it also has biome dependency.

**Comment by BONNe** [comment]
Updating to the Extra Mobs 1.12 will fix your issue.
https://github.com/BentoBoxWorld/ExtraMobs/releases/tag/1.12

**Comment by mrfloris** [comment]
Thank you!
