### ISSUE TITLE
AcidIsland failed to start

### ISSUE THREAD

**Issue by JulyYoLo** [BentoBoxWorld/AcidIsland#143]
### Expected behavior

AcidIsland tart

### Observed/Actual behavior

AcidIsland failed to start

### Steps/models to reproduce

[11:36:06] [Server thread/ERROR]: [BentoBox] Skipping AcidIsland due to an unhandled exception...
[11:36:06] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException: Cannot invoke "org.bukkit.World.setDifficulty(org.bukkit.Difficulty)" because "w" is null
        at world.bentobox.bentobox.managers.AddonsManager.seedWorld(AddonsManager.java:367)
        at world.bentobox.bentobox.managers.AddonsManager.createSeedWorlds(AddonsManager.java:352)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:319)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:262)
        at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:190)
        at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:173)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:419)
        at net.minecraft.server.MinecraftServer.handler$zbe000$banner$processStart(MinecraftServer.java:2533)
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java)
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283)
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2133)
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:833)

### BentoBox version

1.18.0
1.18.1SNAPSHOT-b999.jar

### Plugin list

BentoBox-1.24.1.jar
（only）

### Other

JDK 17
Windows11
Spigot

**Comment by JulyYoLo** [comment]
Server ver is 1.20.1

**Comment by tastybento** [comment]
Can you run 'bbox v' in the console and copy and paste the output here?

**Comment by tastybento** [comment]
Cannot replicate, sorry.

1. Go to https://download.bentobox.world.
2. Download the AcidIsland zip pack on the front page
3. Download latests paper from https://papermc.io/downloads/paper
4. Install everything and run
5. Works.

Output of `bbox v`:

```
> bbox v
[16:18:41 INFO]: Running PAPER 1.20.1.
[16:18:41 INFO]: BentoBox version: 1.24.1
[16:18:41 INFO]: Database: JSON
[16:18:41 INFO]: Loaded Game Worlds:
[16:18:41 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[16:18:41 INFO]: Loaded Addons:
[16:18:41 INFO]: AcidIsland 1.18.0 (ENABLED)
[16:18:41 INFO]: Bank 1.7.0 (DISABLED)
[16:18:41 INFO]: Biomes 2.1.1 (ENABLED)
[16:18:41 INFO]: Challenges 1.2.0 (ENABLED)
[16:18:41 INFO]: ControlPanel 1.13.0 (ENABLED)
[16:18:41 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[16:18:41 INFO]: Level 2.11.0 (ENABLED)
[16:18:41 INFO]: Warps 1.13.0 (ENABLED)
```
