### ISSUE TITLE
[1.14.3 Dev build] The acidisland flags fails after bentobox versions #1269.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/AcidIsland#53]
> [11:47:42] [Server thread/ERROR]: [BentoBox] Skipping AcidIsland due to an unhandled exception...
[11:47:42] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException
	at world.bentobox.bentobox.api.flags.Flag.setDefaultSetting(Flag.java:163)
	at world.bentobox.acidisland.AcidIsland.createWorlds(AcidIsland.java:106)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:162)
	at java.util.ArrayList.forEach(Unknown Source)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:147)
	at world.bentobox.bentobox.BentoBox.lambda$onEnable$1(BentoBox.java:171)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
	at java.lang.Thread.run(Unknown Source)

#### Server
 - OS: **Windows**
 - Java version: **8**

#### Plugins
![image](https://user-images.githubusercontent.com/47111280/61181406-d2643600-a62e-11e9-9c98-7afea25f22e8.png)

##### BentoBox and Addons

```
Bentobox version  #1269 and uppers
```

##### Configuration
 - Database: **YAML**

**Comment by tastybento** [comment]
Should be fixed with latest AcidIsland build.
