### ISSUE TITLE
isOnJoinResetHealth() WARN and isOnLeaveResetHealth() ERROR

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#68]
#### Describe the bug

The plugin sometimes write this error.

#### Steps to reproduce the behavior

Maybe /is create and /is team accept

#### Expected behavior

The plugin no write this error.

#### Server

 - OS: **Ubuntu**
 - Java version: **11.0.4**

#### Plugins

```
Plugins (89): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, ArmorStandEditor, BentoBox, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomCrafting, CustomOreGen, Duels, EnderContainers, EntityDetection, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, HeadDatabase*, HolographicDisplays, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv, PickupSpawners, PlaceholderAPI, PlugMan, PocketGames, PomaAdditions, ProtocolLib, RedstoneClockDetector, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge
```

##### BentoBox and Addons

```
[10:19:58 INFO]: BentoBox version: 1.9.0-SNAPSHOT-b1437
[10:19:58 INFO]: Database: JSON
[10:19:58 INFO]: Loaded Game Worlds:
[10:19:58 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[10:19:58 INFO]: Loaded Addons:
[10:19:58 INFO]: AcidIsland 1.8.0-SNAPSHOT-b481 (ENABLED)
[10:19:58 INFO]: Biomes 1.6.0.2-SNAPSHOT-b142 (ENABLED)
[10:19:58 INFO]: Challenges 0.9.0-SNAPSHOT-#383 (ENABLED)
[10:19:58 INFO]: DimensionalTrees 1.6.0-SNAPSHOT (ENABLED)
[10:19:58 INFO]: Greenhouses 0.4.2-SNAPSHOT (ENABLED)
[10:19:58 INFO]: Level 1.8.0 (ENABLED)
[10:19:58 INFO]: Likes 1.7.0-SNAPSHOT-#7 (ENABLED)
[10:19:58 INFO]: Limits 1.7.0-SNAPSHOT-b170 (ENABLED)
[10:19:58 INFO]: Warps 1.8.0-SNAPSHOT-b187 (ENABLED)
```

##### Configuration

 - Database: **JSON** 

### Additional context

```
[22:30:11] [Server thread/WARN]: [BentoBox] Task #2417639 for BentoBox v1.9.0-SNAPSHOT-b1437 generated an exception
java.lang.AbstractMethodError: Receiver class world.bentobox.acidisland.AISettings does not define or inherit an implementation of the resolved method 'abstract boolean isOnJoinResetHealth()' of interface world.bentobox.bentobox.api.configuration.WorldSettings.
	at world.bentobox.bentobox.managers.IslandWorldManager.isOnJoinResetHealth(IslandWorldManager.java:538) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.cleanPlayer(IslandTeamInviteAcceptCommand.java:175) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.acceptTeamInvite(IslandTeamInviteAcceptCommand.java:130) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.lambda$execute$2(IslandTeamInviteAcceptCommand.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

```
[11:00:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.9.0-SNAPSHOT-b1437
java.lang.AbstractMethodError: Receiver class world.bentobox.acidisland.AISettings does not define or inherit an implementation of the resolved method 'abstract boolean isOnLeaveResetHealth()' of interface world.bentobox.bentobox.api.configuration.WorldSettings.
	at world.bentobox.bentobox.managers.IslandWorldManager.isOnLeaveResetHealth(IslandWorldManager.java:601) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandResetCommand.lambda$kickMembers$3(IslandResetCommand.java:203) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandResetCommand.kickMembers(IslandResetCommand.java:158) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandResetCommand.resetIsland(IslandResetCommand.java:125) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.IslandResetCommand.execute(IslandResetCommand.java:92) ~[?:?]
	at world.bentobox.bentobox.panels.IslandCreationPanel.lambda$openPanel$1(IslandCreationPanel.java:53) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1014.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-221]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by BONNe** [comment]
Yea... you are using an incompatible version of AcidIsland for your BentoBox.

If you use BentoBox 1.9-SNAPSHOT it is likely that you will need yo update AcidIsland too.
It is just how it works.

**Comment by andris155** [comment]
Thanks
