### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#96]
Hi, how come when through the nether portal I get this error from Multiverse? It didn't happen before

```
[19:19:05 ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-b719
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor697.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-185]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityPlayer.callPortalEvent(EntityPlayer.java:997) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.Entity.a(Entity.java:2629) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityPlayer.a(EntityPlayer.java:863) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:916) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.Entity.doPortalTick(Entity.java:2163) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:432) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:266) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:407) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2429) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:156) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:508) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:163) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda
```

**Comment by BONNe** [comment]
You could try by removing or updating Multiverse.

It is not  necessary for bentobox, but if you have other worlds and you need it, and updating do not help, then you need to ask support in for Multiverse developers.
